services:
  client:
    image: client:latest
    build:
      dockerfile: ./build/Dockerfile
    tty: true
    stdin_open: true
    environment:
      HOST: storage
      PORT: 8080

  storage:
    image: storage:latest
    build:
      dockerfile: ./build/DockerfileService

