services:
  client:
    image: client:latest
    build:
      dockerfile: ./build/Dockerfile
    tty: true
    stdin_open: true
    environment:
      HOST: "${HOST}"
      PORT: "${PORT}"
    volume:
      "./ssTables:/ssTables"

  storage:
    image: storage:latest
    build:
      dockerfile: ./build/DockerfileService

